version: '3'
services:
  n8n:
    image: n8nio/n8n:latest
    environment:
      - N8N_BASIC_AUTH_ACTIVE=true
      - N8N_BASIC_AUTH_USER=umerahm3d
      - N8N_BASIC_AUTH_PASSWORD=Luminarc1234!
    ports:
      - "5678:5678"
